version: '3'
services: 
  testlink-metrics:
    container_name: testlink-metrics
    image: bxwill/testlink-metrics
    restart: always
    ports:
      - 80:80
    environment:
      TESTLINK_URL: ''      # Required: URL of TestLink
      TESTLINK_USER: ''     # Required: Username in TestLink
      TESTLINK_DEVKEY: ''   # Required: Dev Key of the TestLink Username
      TESTLINK_ITS: ''      # Optional: Issue Tracker System Name in TestLink
