name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
    tags: []

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bxwill/testlink-metrics:${{ github.ref }}
    - name: Push the Docker image
      run: docker push bxwill/testlink-metrics:${{ github.ref }}
